"""Export markdown research reports as styled HTML / PDF / DOCX.

Uses the canonical CSS from canonical_style.css — do not modify that file.

PDF export requires weasyprint (optional; system deps: libpango, libcairo, gdk-pixbuf).
DOCX export requires python-docx (pure Python, no system deps).
"""

from datetime import datetime
from pathlib import Path

CSS_PATH = Path(__file__).parent / "canonical_style.css"


def _load_css() -> str:
    return CSS_PATH.read_text() if CSS_PATH.exists() else ""


def markdown_to_html(md_content: str, title: str = "Research Report") -> str:
    """Convert markdown to styled HTML using the canonical CSS."""
    import markdown

    html_body = markdown.markdown(
        md_content,
        extensions=["tables", "fenced_code", "toc", "nl2br"],
    )
    css = _load_css()
    timestamp = datetime.now().strftime("%B %d, %Y at %I:%M %p")

    return f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{title}</title>
    <style>
{css}
    </style>
</head>
<body>
    <div class="header">
        <h1>{title}</h1>
        <p style="color: #666;">Generated by Gemini Deep Research</p>
        <p style="color: #888; font-size: 0.9em;">{timestamp}</p>
    </div>
    {html_body}
    <div class="generated" style="margin-top:40px;color:#888;font-size:0.85em;text-align:center;">
        Generated using Gemini Deep Research Agent
    </div>
</body>
</html>"""


def markdown_to_pdf_bytes(md_content: str, title: str = "Research Report") -> bytes:
    """Render markdown → styled HTML → PDF bytes via weasyprint.

    Raises ImportError if weasyprint is not installed.
    """
    from weasyprint import HTML  # type: ignore

    html = markdown_to_html(md_content, title)
    return HTML(string=html).write_pdf()


def markdown_to_docx_bytes(md_content: str, title: str = "Research Report") -> bytes:
    """Render markdown into a DOCX document and return the bytes.

    Uses python-docx. Not as pretty as the HTML/PDF — no CSS, just heading/paragraph
    structure. Use HTML or PDF if design matters.
    """
    import io
    import re

    from docx import Document
    from docx.shared import Pt

    doc = Document()
    doc.add_heading(title, level=0)
    doc.add_paragraph(f"Generated {datetime.now().strftime('%B %d, %Y at %I:%M %p')}").runs[
        0
    ].font.size = Pt(9)

    # Very simple markdown-to-docx: handle headings, bullet lists, paragraphs.
    lines = md_content.splitlines()
    for line in lines:
        stripped = line.rstrip()
        if not stripped:
            continue
        h_match = re.match(r"^(#{1,6})\s+(.*)$", stripped)
        if h_match:
            level = min(len(h_match.group(1)), 4)
            doc.add_heading(h_match.group(2), level=level)
            continue
        if stripped.startswith(("- ", "* ")):
            doc.add_paragraph(stripped[2:], style="List Bullet")
            continue
        if re.match(r"^\d+\.\s+", stripped):
            doc.add_paragraph(re.sub(r"^\d+\.\s+", "", stripped), style="List Number")
            continue
        doc.add_paragraph(stripped)

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()
